# This is a basic workflow to help you get started with Actions

name: Proves de CI de la Calculadora

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fem_un_checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Instala el flask
        run: pip3 install flask

      # Runs a set of commands using the runners shell
      - name: Executa la app
        run: python3 api_calculadora.py &

      - name: suma
        run: curl http://127.0.0.1:5000/suma/2/2 | grep '{"resultat":4}'

      - name: resta
        run: curl http://127.0.0.1:5000/resta/8/4 | grep '{"resultat":4}'

      - name: multiplica
        run: curl http://127.0.0.1:5000/multiplica/2/2 | grep '{"resultat":4}'

      - name: divideix
        run: curl http://127.0.0.1:5000/divideix/8/2 | grep '{"resultat":4.0}'

